language: c

addons:
    apt:
        packages:
            - doxygen
            - graphviz

script:
    - cd build
    - cmake ../doc -DBUILD_HTML_DOCUMENTATION=ON -DBUILD_MAN_PAGES=OFF
    - make

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: $TRAVIS_BUILD_DIR/build/html
    github_token: $GITHUB_TOKEN
    on:
        branch: master
