FROM debian:9

RUN apt-get update

RUN apt-get -y install git

# build tools
RUN apt-get -y install gcc cmake make pkg-config

# SDK build dependencies
RUN apt-get -y install libjson-c-dev libwebsockets-dev

# examples build dependencies
RUN apt-get -y install libev-dev libncurses5-dev

# documentation build dependencies
RUN apt-get -y install doxygen

RUN apt-get -y install dpkg-dev

RUN apt-get -y clean

COPY build.sh /var/build/

ENV package_flavour debian9

CMD /var/build/build.sh
