FROM fedora:28

# build tools
RUN dnf install -y cmake gcc make pkgconfig

# SDK build dependencies
RUN dnf install -y json-c-devel libwebsockets-devel openssl-devel systemd-devel libev-devel libcurl-devel readline-devel

# documentation build dependencies
RUN dnf install -y doxygen

RUN dnf install -y rpm-build

VOLUME /tmp/webcom-sdk-c/