FROM fedora:24

RUN dnf install -y git

# build tools
RUN dnf install -y cmake gcc make pkgconfig

# SDK build dependencies
RUN dnf install -y json-c-devel libwebsockets-devel openssl-devel

# examples build dependencies
RUN dnf install -y libev-devel ncurses-devel

# documentation build dependencies
RUN dnf install -y doxygen

RUN dnf install -y rpm-build

RUN dnf -y clean all

COPY build.sh /var/build/

ENV package_flavour fedora24

CMD /var/build/build.sh
