FROM ubuntu:17.04

RUN apt-get update

RUN apt-get -y install git

# build tools
RUN apt-get -y install gcc cmake make pkg-config

# SDK build dependencies
RUN apt-get -y install libjson-c-dev libwebsockets-dev libsystemd-dev

# event loop integrations
RUN apt -y install libev-dev libuv1-dev libevent-dev

# examples build dependencies
RUN apt-get -y install libev-dev libncurses5-dev

# documentation build dependencies
RUN apt-get -y install doxygen

RUN apt-get -y install dpkg-dev

RUN apt-get -y clean

COPY build.sh /var/build/

ENV package_flavour ubuntu17.04

VOLUME /tmp/webcom-package/

CMD /var/build/build.sh -DWITH_LIBEV=ON -DWITH_LIBUV=ON -DWITH_LIBEVENT=ON
